import * as fs from "node:fs";
import * as path from "node:path";
import type { Plugin } from "@voidzero-dev/vite-plus-core";

export interface InlineAssetsOptions {
  outPath: string;
  /** Vite output dir of the web build (where main.js / *.css land). */
  webOutDir: string;
}

/**
 * Vite plugin that, after the web build finishes, reads the emitted main.js
 * + CSS from disk and writes `src/ui/assets.ts` exporting the inlined HTML
 * string. This keeps the node (library) build self-contained: it imports
 * WEB_HTML from ./assets.ts as ordinary source, so the final
 * dist/mcp/server.js embeds the whole web page without shipping extra files.
 *
 * Runs in `closeBundle` (everything already written to disk) and reads the
 * output directory directly — the StyleX CSS asset is injected into the
 * bundle too late for generateBundle to see it.
 */
export function inlineAssetsPlugin(options: InlineAssetsOptions): Plugin {
  return {
    name: "zcode-inline-assets",
    apply: "build",
    enforce: "post",
    closeBundle() {
      const webDir = path.resolve(options.webOutDir);
      const collect = (ext: string): string =>
        walk(webDir)
          .filter((f) => f.endsWith(ext))
          .sort()
          .map((f) => fs.readFileSync(f, "utf8"))
          .join("\n");

      const js = collect(".js");
      const css = collect(".css");
      if (!js) throw new Error(`[inline-assets] no .js output found in ${webDir}`);

      const html = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark">
<title>ZCode 模型配置</title>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script>${js}</script>
</body>
</html>`;

      const outPath = path.resolve(options.outPath);
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      const banner = `// GENERATED FILE — DO NOT EDIT. Regenerated by \`vite build --mode web\`.\n`;
      fs.writeFileSync(outPath, `${banner}export const WEB_HTML = ${JSON.stringify(html)};\n`);
      console.log(
        `[inline-assets] wrote ${options.outPath} (js ${js.length}B, css ${css.length}B)`,
      );
    },
  };
}

function walk(dir: string): string[] {
  const out: string[] = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile()) out.push(full);
  }
  return out;
}
