import * as stylex from "@stylexjs/stylex";

/**
 * Design tokens — modern dark "AI console" language:
 * deep layered surfaces, violet-blue accent, subtle borders,
 * generous rounding, quiet meta text.
 */
const colors = {
  bg: "var(--mc-bg)",
  bgPanel: "var(--mc-panel)",
  bgPanelHover: "var(--mc-panel-hover)",
  bgElevated: "var(--mc-elevated)",
  bgInput: "var(--mc-input)",
  bgInset: "var(--mc-inset)",
  border: "var(--mc-border)",
  borderStrong: "var(--mc-border-strong)",
  text: "var(--mc-text)",
  textDim: "var(--mc-text-dim)",
  textFaint: "var(--mc-text-faint)",
  accent: "var(--mc-accent)",
  accentSolid: "var(--mc-accent-solid)",
  accentSoft: "rgba(110,124,244,0.14)",
  success: "var(--mc-success)",
  successSoft: "rgba(74,222,128,0.12)",
  warn: "var(--mc-warn)",
  warnSoft: "rgba(251,191,36,0.12)",
  danger: "var(--mc-danger)",
  dangerSoft: "rgba(248,113,113,0.1)",
};

const fonts = {
  sans:
    "'Inter', -apple-system, 'SF Pro Text', 'PingFang SC', 'Segoe UI', sans-serif",
  mono: "'JetBrains Mono', 'SF Mono', ui-monospace, Consolas, monospace",
};

const radii = { card: "14px", control: "8px", chip: "999px" };

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    backgroundColor: colors.bg,
    color: colors.text,
    fontFamily: fonts.sans,
    fontSize: "13.5px",
    lineHeight: 1.55,
    display: "flex",
    flexDirection: "column",
    WebkitFontSmoothing: "antialiased",
  },

  /* ── Header ─────────────────────────────────────────────── */
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    padding: "14px 24px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    backgroundColor: `linear-gradient(180deg, ${colors.bgPanel}, ${colors.bg})`,
    flexWrap: "wrap",
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    flexWrap: "wrap",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  title: {
    fontSize: "15px",
    fontWeight: 650,
    letterSpacing: "-0.01em",
    margin: 0,
    whiteSpace: "nowrap",
  },
  scopeTabs: {
    display: "flex",
    gap: "2px",
    padding: "3px",
    borderRadius: "10px",
    backgroundColor: colors.bgInset,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
  },
  tab: {
    padding: "5px 14px",
    backgroundColor: "transparent",
    color: colors.textDim,
    borderWidth: "0px",
    borderStyle: "none",
    borderColor: "transparent",
    borderRadius: "7px",
    cursor: "pointer",
    fontSize: "12.5px",
    fontWeight: 500,
    fontFamily: fonts.sans,
    transition: "color 0.15s ease, background-color 0.15s ease",
    ":hover": { color: colors.text },
  },
  tabActive: {
    backgroundColor: colors.bgElevated,
    color: colors.text,
    boxShadow: `0 1px 2px rgba(0,0,0,0.4), inset 0 0 0 1px ${colors.borderStrong}`,
  },
  pathChip: {
    fontSize: "11.5px",
    color: colors.textFaint,
    fontFamily: fonts.mono,
    backgroundColor: colors.bgInput,
    padding: "4px 10px",
    borderRadius: radii.chip,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    maxWidth: "340px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  roleSelect: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
  },
  roleLabel: {
    fontSize: "11px",
    color: colors.textFaint,
    fontFamily: fonts.mono,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },

  /* ── Controls ───────────────────────────────────────────── */
  select: {
    appearance: "none",
    backgroundColor: colors.bgInput,
    color: colors.text,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.control,
    padding: "6px 28px 6px 10px",
    fontSize: "12.5px",
    fontFamily: fonts.sans,
    maxWidth: "240px",
    outline: "none",
    backgroundImage:
      "url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6' viewBox='0 0 10 6'%3E%3Cpath fill='%235c6475' d='M0 0l5 6 5-6z'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 10px center",
    transition: "border-color 0.15s ease",
    ":hover": { borderColor: colors.borderStrong },
    ":focus-visible": { borderColor: colors.accent },
  },
  input: {
    backgroundColor: colors.bgInput,
    color: colors.text,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.control,
    padding: "7px 11px",
    fontSize: "13px",
    fontFamily: fonts.sans,
    width: "100%",
    boxSizing: "border-box",
    outline: "none",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
    "::placeholder": { color: colors.textFaint },
    ":hover": { borderColor: colors.borderStrong },
    ":focus": {
      borderColor: colors.accentSolid,
      boxShadow: `0 0 0 3px ${colors.accentSoft}`,
    },
  },
  inputMono: {
    fontFamily: fonts.mono,
    fontSize: "12.5px",
  },
  buttonPrimary: {
    backgroundColor: colors.accentSolid,
    color: "#ffffff",
    borderWidth: "0px",
    borderStyle: "none",
    borderColor: "transparent",
    borderRadius: radii.control,
    padding: "7px 18px",
    fontSize: "12.5px",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: fonts.sans,
    boxShadow: "var(--mc-shadow-control)",
    transition: "background-color 0.15s ease, box-shadow 0.15s ease",
    ":hover": {
      backgroundColor: colors.accent,
      boxShadow: "var(--mc-shadow-control-hover)",
    },
    ":disabled": { opacity: 0.5, cursor: "not-allowed" },
  },
  buttonGhost: {
    backgroundColor: "transparent",
    color: colors.textDim,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.control,
    padding: "7px 14px",
    fontSize: "12.5px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.sans,
    transition: "color 0.15s ease, border-color 0.15s ease, background-color 0.15s ease",
    ":hover": {
      color: colors.text,
      borderColor: colors.borderStrong,
      backgroundColor: colors.bgPanelHover,
    },
  },
  buttonDanger: {
    backgroundColor: "transparent",
    color: colors.danger,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.control,
    padding: "7px 14px",
    fontSize: "12.5px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.sans,
    ":hover": {
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
    },
  },
  buttonSmall: {
    backgroundColor: "transparent",
    color: colors.textFaint,
    borderWidth: "0px",
    borderStyle: "none",
    borderColor: "transparent",
    borderRadius: "6px",
    padding: "4px 10px",
    fontSize: "12px",
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: fonts.sans,
    opacity: 0.45,
    transition: "opacity 0.12s ease, color 0.12s ease, background-color 0.12s ease",
    ":hover": { color: colors.danger, backgroundColor: colors.dangerSoft },
  },

  /* ── Layout ─────────────────────────────────────────────── */
  main: {
    display: "flex",
    flex: 1,
    minHeight: 0,
  },
  sidebar: {
    width: "248px",
    borderRightWidth: "1px", borderRightStyle: "solid", borderRightColor: colors.border,
    padding: "16px 12px",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    overflowY: "auto",
    backgroundColor: colors.bg,
  },
  sidebarTitle: {
    fontSize: "10.5px",
    fontWeight: 600,
    color: colors.textFaint,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    margin: "2px 6px 10px",
  },
  providerItem: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    padding: "9px 12px",
    borderRadius: "10px",
    cursor: "pointer",
    borderWidth: "1px", borderStyle: "solid", borderColor: "transparent",
    backgroundColor: "transparent",
    textAlign: "left",
    color: colors.textDim,
    fontFamily: fonts.sans,
    fontSize: "13px",
    width: "100%",
    marginBottom: "2px",
    transition: "background-color 0.12s ease, border-color 0.12s ease",
    ":hover": { backgroundColor: colors.bgPanelHover },
  },
  providerItemActive: {
    backgroundColor: colors.bgPanelHover,
    borderColor: colors.borderStrong,
    color: colors.text,
  },
  providerItemTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    width: "100%",
  },
  providerName: {
    fontWeight: 600,
    color: "inherit",
  },
  providerMeta: {
    fontSize: "11px",
    color: colors.textFaint,
    fontFamily: fonts.mono,
  },
  roleBadge: {
    fontSize: "9.5px",
    fontWeight: 600,
    letterSpacing: "0.05em",
    color: colors.accent,
    backgroundColor: colors.accentSoft,
    padding: "1px 7px",
    borderRadius: radii.chip,
    fontFamily: fonts.mono,
    textTransform: "uppercase",
  },
  sidebarFooter: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "14px",
    paddingTop: "14px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
  },
  detail: {
    flex: 1,
    padding: "24px 28px 56px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    backgroundColor: colors.bg,
  },

  /* ── Panels & forms ─────────────────────────────────────── */
  panel: {
    backgroundColor: colors.bgPanel,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.card,
    padding: "20px 22px",
  },
  sectionTitle: {
    fontSize: "13.5px",
    fontWeight: 650,
    letterSpacing: "-0.01em",
    margin: "0 0 16px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "16px",
  },
  formGridTwo: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "16px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  fieldLabel: {
    fontSize: "11.5px",
    fontWeight: 500,
    color: colors.textDim,
    letterSpacing: "0.01em",
  },
  muted: {
    color: colors.textDim,
    fontSize: "13px",
    margin: 0,
  },

  /* ── Model table ────────────────────────────────────────── */
  tableToolbar: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "14px",
  },
  modelTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
  },
  modelHeaderRow: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.borderStrong,
  },
  modelHeaderCell: {
    padding: "6px 10px",
    textAlign: "left",
    fontSize: "10.5px",
    fontWeight: 600,
    color: colors.textFaint,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    paddingBottom: "8px",
  },
  modelRow: {
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    cursor: "pointer",
    transition: "background-color 0.1s ease",
    ":hover": { backgroundColor: colors.bgPanelHover },
  },
  modelRowExpanded: {
    backgroundColor: colors.bgPanelHover,
  },
  modelCell: {
    padding: "10px 10px",
    textAlign: "left",
    verticalAlign: "middle",
  },
  modelCellRight: {
    padding: "10px 10px",
    textAlign: "right",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  },

  /* ── Chips ──────────────────────────────────────────────── */
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "11px",
    padding: "2px 9px",
    borderRadius: radii.chip,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    color: colors.textFaint,
    backgroundColor: colors.bgInset,
    fontFamily: fonts.mono,
    marginLeft: "5px",
    whiteSpace: "nowrap",
  },
  chipOn: {
    color: colors.success,
    borderColor: "transparent",
    backgroundColor: colors.successSoft,
  },
  bannerWarn: {
    backgroundColor: colors.warnSoft,
    color: colors.warn,
    padding: "9px 24px",
    fontSize: "12.5px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  bannerOk: {
    backgroundColor: colors.successSoft,
    color: colors.success,
    padding: "9px 24px",
    fontSize: "12.5px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },

  /* ── Dialogs ────────────────────────────────────────────── */
  dialogBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(4,5,8,0.7)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: "24px",
  },
  dialog: {
    backgroundColor: colors.bgPanel,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.borderStrong,
    borderRadius: "16px",
    width: "min(880px, 100%)",
    maxHeight: "88vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "var(--mc-shadow-dialog)",
  },
  dialogHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  dialogTitle: {
    fontSize: "14.5px",
    fontWeight: 650,
    margin: 0,
    letterSpacing: "-0.01em",
  },
  dialogBody: {
    padding: "18px 20px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  dialogFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "10px",
    padding: "14px 20px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.border,
  },
  filterRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12.5px",
    color: colors.textDim,
    cursor: "pointer",
  },
  catalogList: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "44vh",
    overflowY: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: "10px",
    backgroundColor: colors.bgInput,
  },
  catalogItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "9px 14px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    cursor: "pointer",
    transition: "background-color 0.1s ease",
    ":hover": { backgroundColor: colors.bgPanelHover },
  },
  catalogProvider: {
    fontSize: "11px",
    color: colors.textFaint,
    fontFamily: fonts.mono,
    minWidth: "110px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  catalogModel: {
    fontWeight: 600,
    fontSize: "13px",
    whiteSpace: "nowrap",
  },
  catalogDesc: {
    fontSize: "12px",
    color: colors.textDim,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pre: {
    fontFamily: fonts.mono,
    fontSize: "12px",
    lineHeight: 1.6,
    backgroundColor: colors.bgInset,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: "10px",
    padding: "14px",
    margin: 0,
    maxHeight: "42vh",
    overflow: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    color: colors.textDim,
  },

  /* ── Switch rows (model editor) ─────────────────────────── */
  switchGroup: {
    display: "flex",
    flexDirection: "column",
    marginTop: "4px",
  },
  switchRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "10px 0",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  switchRowLast: {
    borderBottom: "none",
  },
  switchLabel: {
    fontSize: "13px",
    fontWeight: 500,
  },
  switchHint: {
    fontSize: "11px",
    color: colors.textFaint,
    marginTop: "1px",
  },
  toggle: {
    appearance: "none",
    flexShrink: 0,
    width: "34px",
    height: "19px",
    borderRadius: radii.chip,
    backgroundColor: colors.borderStrong,
    position: "relative",
    cursor: "pointer",
    borderWidth: "0px",
    borderStyle: "none",
    borderColor: "transparent",
    transition: "background-color 0.18s ease",
    "::after": {
      content: "' '",
      position: "absolute",
      top: "2px",
      left: "2px",
      width: "15px",
      height: "15px",
      borderRadius: radii.chip,
      backgroundColor: "#ffffff",
      boxShadow: "0 1px 2px rgba(0,0,0,0.4)",
      transition: "left 0.18s ease",
    },
  },
  toggleOn: {
    backgroundColor: colors.success,
    "::after": { left: "17px" },
  },
  textarea: {
    backgroundColor: colors.bgInput,
    color: colors.textDim,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: "10px",
    padding: "12px 14px",
    fontSize: "12px",
    fontFamily: fonts.mono,
    lineHeight: 1.6,
    width: "100%",
    minHeight: "90px",
    boxSizing: "border-box",
    resize: "vertical",
    outline: "none",
    transition: "border-color 0.15s ease",
    ":focus": {
      borderColor: colors.accentSolid,
      color: colors.text,
    },
  },

  /* ── Custom Select menu ─────────────────────────────────── */
  selectTrigger: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    minWidth: "150px",
    maxWidth: "260px",
    backgroundColor: colors.bgInput,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: radii.control,
    padding: "6px 10px",
    fontSize: "12.5px",
    fontFamily: fonts.sans,
    cursor: "pointer",
    textAlign: "left",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
    ":hover": { borderColor: colors.borderStrong },
    ":focus-visible": { borderColor: colors.accentSolid, boxShadow: `0 0 0 3px ${colors.accentSoft}` },
  },
  selectTriggerWide: {
    width: "100%",
    maxWidth: "100%",
  },
  selectValue: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  selectPlaceholder: {
    color: colors.textFaint,
  },
  selectCaret: {
    flexShrink: 0,
    transition: "transform 0.15s ease",
  },
  selectCaretOpen: {
    transform: "rotate(180deg)",
  },
  menuBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 90,
  },
  menuPanel: {
    position: "absolute",
    zIndex: 95,
    minWidth: "220px",
    maxWidth: "340px",
    maxHeight: "320px",
    overflowY: "auto",
    backgroundColor: colors.bgElevated,
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: "10px",
    padding: "5px",
    boxShadow: "var(--mc-shadow-dialog)",
  },
  menuGroup: {
    fontSize: "10.5px",
    fontWeight: 600,
    color: colors.textFaint,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    padding: "7px 10px 4px",
    position: "sticky",
    top: 0,
    backgroundColor: colors.bgElevated,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    width: "100%",
    padding: "7px 10px",
    borderRadius: "7px",
    borderWidth: "0px",
    borderStyle: "none",
    borderColor: "transparent",
    backgroundColor: "transparent",
    color: colors.textDim,
    fontSize: "12.5px",
    fontFamily: fonts.sans,
    cursor: "pointer",
    textAlign: "left",
    transition: "background-color 0.1s ease, color 0.1s ease",
    ":hover": { backgroundColor: colors.bgPanelHover, color: colors.text },
  },
  menuItemActive: {
    backgroundColor: colors.accentSoft,
    color: colors.text,
  },
  menuItemCheck: {
    color: colors.accent,
    flexShrink: 0,
  },
  menuItemHint: {
    color: colors.textFaint,
    fontSize: "11px",
  },
  menuEmpty: {
    padding: "12px 10px",
    fontSize: "12px",
    color: colors.textFaint,
  },
  /* ── Icon helpers ───────────────────────────────────────── */
  iconOnly: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "7px 9px",
  },
  iconWithGap: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  icon14: {
    flexShrink: 0,
  },
  inputIconWrap: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    maxWidth: "280px",
  },
  inputIconLead: {
    position: "absolute",
    left: "10px",
    color: colors.textFaint,
    pointerEvents: "none",
    display: "flex",
    alignItems: "center",
  },
  inputWithLead: {
    paddingLeft: "32px",
  },
  themeTab: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "5px 9px",
  },
  chipIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },

  /* ── Modality chips & auto-match ────────────────────────── */
  modChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    borderRadius: "999px",
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.bgInput,
    color: colors.textDim,
    fontSize: "12.5px",
    fontWeight: 500,
    fontFamily: fonts.sans,
    cursor: "pointer",
    transition: "all 0.12s ease",
    ":hover": { borderColor: colors.borderStrong },
  },
  modChipOn: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accentSolid,
    color: colors.accent,
  },
  modChipLocked: {
    opacity: 0.7,
    cursor: "default",
  },
  matchBar: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "10px 14px",
    borderRadius: "10px",
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.accentSoft,
  },
  matchRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  matchText: {
    flex: 1,
    fontSize: "12.5px",
    color: colors.textDim,
  },
  matchStrong: {
    color: colors.text,
    fontWeight: 600,
  },
  matchApply: {
    backgroundColor: colors.accentSolid,
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    padding: "4px 12px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: fonts.sans,
    ":hover": { backgroundColor: colors.accent },
  },
  noMatchText: {
    fontSize: "12px",
    color: colors.textFaint,
    margin: 0,
  },

  errorText: {
    color: colors.danger,
    fontSize: "12px",
    fontFamily: fonts.mono,
    whiteSpace: "pre-wrap",
  },
});
